### ISSUE TITLE
Ask Taylor questions

### ISSUE THREAD

**Issue by jessemillar** [Snap-for-Windows/snap#3]

**Comment by devingd** [comment]
The Questions for Taylor that I have from the meetings are:
- [x] Use case of using Snap? For perfmon? AD?
- [x] Are our plugins just collectors? Do we need to process the data at all? publish?
- [x] DB to store Snap information?
- [x] Minimum viable product?
- [x] Slack channel?

**Comment by Meinfield** [comment]
Plugins will output text files
Don't worry about databases (output text files)
*See Project Definition Document
