### ISSUE TITLE
Make an MSI installer

### ISSUE THREAD

**Issue by jessemillar** [Snap-for-Windows/snap#31]
On first glance, the [WiX](http://wixtoolset.org/) framework seems promising.

**Comment by devingd** [comment]
@jcooklin referenced these in #2 and thought they were applicable more to this issue, so I'm copy/pasting it here:

> Below are some high priority work items related to build and deploy as I see it:
> - [ ] Start stubbing out Windows section in the README
> - [ ] Create Windows Snap package (MSI)
>     - [ ] Install snap as a service
>         - [ ] What user does the service run as
>         - [ ] What kind of permissions are required
>     - [ ] Define where the default config should exist
>         - [ ] Define the appropriate config values for windows (where should logs go etc)

**Comment by jessemillar** [comment]
[This tutorial](https://www.firegiant.com/wix/tutorial/) looks good. Perusing now.

**Comment by jessemillar** [comment]
"The toolset is written in C# and requires the .NET Framework to run. However, this only applies to the toolset itself. The installation packages you create with the toolset do not require any extra framework or software to be installed on the target computer."

**Comment by jessemillar** [comment]
While I haven't verified these personally, [these examples](https://github.com/rstropek/Samples/tree/master/WiXSamples) look promising.

**Comment by jessemillar** [comment]
@jcooklin Do we care about signing the MSI?

**Comment by jessemillar** [comment]
Development [here](https://github.com/Snap-for-Windows/snap/tree/feature/msi/msi).

**Comment by jessemillar** [comment]
It looks like there might be [a wizard](http://wixtoolset.org/documentation/manual/v3/votive/authoring_first_votive_project.html) for making WiX installers?

[Here](http://robmensching.com/blog/posts/2007/11/20/wix-editors/) is a list of WiX editors. Any should be fine as long as we target WiX v3.

**Comment by devingd** [comment]
Used the wizard above and in less than 10 minutes was able to generate a simple MSI which stuck the snap.exe into the Program Files directory. Haven't really looked into the other options yet, but WiX Edit seems promising.
