### ISSUE TITLE
Look at Active Directory

### ISSUE THREAD

**Issue by jessemillar** [Snap-for-Windows/snap#5]

**Comment by Meinfield** [comment]
Some potential scripts:

Audit Report without elevated privileges - https://gallery.technet.microsoft.com/office/Active-Directory-Audit-7754a877
Export users to CSV - https://gallery.technet.microsoft.com/scriptcenter/Powershell-script-to-5edcdaea/view/Discussions#content
For users in AD - http://woshub.com/get-aduser-getting-active-directory-users-data-via-powershell/

**Comment by Meinfield** [comment]
AD Report creating with Powershell:
https://4sysops.com/archives/create-an-active-directory-report-for-excel-with-powershell/

Note: Everything I've found so far uses powershell

**Comment by jessemillar** [comment]
Using PowerShell doesn't sound like it'll be a huge deal, so don't concern yourself too much with finding alternatives.

https://github.com/Snap-for-Windows/snap/issues/1
