### ISSUE TITLE
Looking into getting Windows Server setup

### ISSUE THREAD

**Issue by jessemillar** [Snap-for-Windows/snap#8]

**Comment by jessemillar** [comment]
"So BYU does not appear to have Windows Server 2016 licenses yet. I have made a hyper visor and am going to set up a Windows server 2012 that we can use until we can get 2016 licenses, from there we can run both on the virtual esx network. Anyone see any issues with that?" @KadeTheKade

**Comment by KadeTheKade** [comment]
The server is up, but I need to finish some stuff to have AD functional. I will work on finishing that up this week as well.

**Comment by devingd** [comment]
@KadeTheKade based on your recent hangouts messages, it sounds like this is complete. Would you say it is completed?
